import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F5F7FB',
  },
  content: {
    padding: 18,
    paddingBottom: 34,
  },
  headerCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 18,
    marginBottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  headerIcon: {
    width: 54,
    height: 54,
    borderRadius: 16,
    backgroundColor: colors.primaryStrong,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  headerIconText: {
    color: colors.white,
    fontSize: 28,
    fontWeight: '900',
  },
  headerText: {
    flex: 1,
  },
  title: {
    color: colors.primary,
    fontSize: 24,
    fontWeight: '800',
    marginBottom: 6,
  },
  subtitle: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 21,
  },
  emptyCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 22,
    marginBottom: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
    marginTop: 10,
    marginBottom: 6,
  },
  emptyText: {
    color: colors.textSecondary,
    textAlign: 'center',
  },
  emptyIcon: {
    color: colors.textSecondary,
    fontSize: 40,
    fontWeight: '900',
  },
  itemCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: colors.border,
  },
  itemPhoto: {
    width: '100%',
    height: 150,
    borderRadius: 16,
    marginBottom: 14,
  },
  itemInfo: {
    marginBottom: 14,
  },
  category: {
    color: colors.secondary,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  itemName: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 6,
  },
  price: {
    color: colors.primaryStrong,
    fontSize: 17,
    fontWeight: '800',
    marginBottom: 4,
  },
  quantity: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  actions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  quantityButton: {
    backgroundColor: colors.accentSoft,
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quantityButtonText: {
    color: '#195C5D',
    fontSize: 20,
    fontWeight: '900',
  },
  quantityValue: {
    color: colors.primary,
    fontSize: 18,
    fontWeight: '900',
    minWidth: 22,
    textAlign: 'center',
  },
  removeButton: {
    backgroundColor: '#FFE4E6',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  removeButtonText: {
    color: '#9F1239',
    fontWeight: '800',
  },
  removeIcon: {
    color: '#9F1239',
    fontSize: 18,
    fontWeight: '900',
  },
  controlCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  paymentCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    padding: 18,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 12,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 12,
  },
  secureBadge: {
    backgroundColor: colors.accentSoft,
    borderRadius: 999,
    paddingVertical: 8,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 12,
  },
  secureText: {
    color: '#195C5D',
    fontSize: 12,
    fontWeight: '800',
  },
  secureIcon: {
    color: '#195C5D',
    fontSize: 14,
    fontWeight: '900',
  },
  choiceOption: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingVertical: 13,
    paddingHorizontal: 14,
    marginBottom: 10,
    backgroundColor: colors.surfaceAlt,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  choiceOptionActive: {
    backgroundColor: colors.primaryStrong,
    borderColor: colors.primaryStrong,
  },
  choiceText: {
    color: colors.text,
    fontWeight: '800',
  },
  choiceIcon: {
    color: colors.primaryStrong,
    fontSize: 22,
    fontWeight: '900',
    width: 24,
    textAlign: 'center',
  },
  choiceIconActive: {
    color: colors.white,
  },
  choiceTextActive: {
    color: colors.white,
  },
  paymentOption: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingVertical: 13,
    paddingHorizontal: 14,
    marginBottom: 10,
    backgroundColor: colors.surfaceAlt,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  paymentOptionActive: {
    backgroundColor: colors.primaryStrong,
    borderColor: colors.primaryStrong,
  },
  paymentCopy: {
    flex: 1,
  },
  paymentIcon: {
    color: colors.primaryStrong,
    fontSize: 24,
    fontWeight: '900',
    width: 28,
    textAlign: 'center',
  },
  paymentIconActive: {
    color: colors.white,
  },
  paymentText: {
    color: colors.text,
    fontWeight: '900',
    marginBottom: 3,
  },
  paymentTextActive: {
    color: colors.white,
  },
  paymentHint: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    marginTop: 4,
  },
  paymentHintActive: {
    color: '#D9E6F2',
  },
  cardFields: {
    marginTop: 4,
  },
  input: {
    backgroundColor: '#F6FAFD',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 10,
  },
  inputRow: {
    flexDirection: 'row',
    gap: 10,
  },
  inputHalf: {
    flex: 1,
  },
  noteInput: {
    minHeight: 82,
    textAlignVertical: 'top',
  },
  totalCard: {
    backgroundColor: colors.primary,
    borderRadius: 20,
    padding: 18,
    marginTop: 4,
    marginBottom: 16,
  },
  totalLabel: {
    color: colors.heroText,
    fontWeight: '700',
    marginBottom: 4,
  },
  totalValue: {
    color: colors.white,
    fontSize: 28,
    fontWeight: '900',
  },
  totalItems: {
    color: colors.heroText,
    marginTop: 6,
  },
  checkoutButton: {
    backgroundColor: colors.secondary,
    borderRadius: 16,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  checkoutButtonDisabled: {
    opacity: 0.5,
  },
  checkoutButtonText: {
    color: colors.white,
    fontWeight: '800',
    fontSize: 16,
  },
  checkoutIcon: {
    color: colors.white,
    fontSize: 18,
    fontWeight: '900',
  },
});
